In [3]:
import pandas as pd
from eda_support_functions import *

In [4]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_info_columns", 1000)

In [5]:
RUNS_IDS = [
    # "20240905_183321",
    # "20240905_231518",
    # "20260206_092929",
    # "20260205_225657"
    '20260207_190503'
    ]

In [6]:
parameters_df = load_metadata(
    "parameters", "/Users/iliasx/Documents/GitHub/box-office-prediction/metadata"
)
experiment_df = load_metadata(
    "metrics", "/Users/iliasx/Documents/GitHub/box-office-prediction/metadata"
)
conf_matrix_df = load_metadata(
    "confusion_matrix", "/Users/iliasx/Documents/GitHub/box-office-prediction/metadata"
)

In [7]:
conf_matrix_df

,run_id,timestamp,model_type,problem_type,dataset_name,grid_type,has_outliers_removed,feature_engineering,scaler,variance_threshold,duration,number_of_combinations,conf_matrix
0,20260207_190503,2026-02-07 19:10:52,random_forest_classifier,binary_classification,full,non_grid,False,none,StandardScaler,0,0.989376,1,"[{'0': 1164, '1': 389}, {'0': 277, '1': 597}]"
1,20260207_190503,2026-02-07 19:10:45,decision_tree_classifier,binary_classification,large_productions,non_grid,True,none,StandardScaler,0,0.019991,1,"[{'0': 191, '1': 241}, {'0': 45, '1': 217}]"
2,20260207_190503,2026-02-07 19:12:56,xgboost_classifier,binary_classification,large_productions,non_grid,True,complex,StandardScaler,0,2.880083,1,"[{'0': 335, '1': 97}, {'0': 112, '1': 150}]"
3,20260207_190503,2026-02-07 19:11:19,logistic_regression,multi_class_classification,small_productions,non_grid,False,none,StandardScaler,0,0.113967,1,"[{'Bankrupt': 297, 'Flop': 75, 'Huge Success':..."
4,20260207_190503,2026-02-07 19:06:30,lightgbm_regressor,regression,small_productions,non_grid,True,none,StandardScaler,0,0.466886,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,20260207_190503,2026-02-07 19:09:25,decision_tree_classifier,multi_class_classification,medium_productions,non_grid,True,complex,StandardScaler,0,0.070245,1,"[{'Bankrupt': 28, 'Flop': 37, 'Huge Success': ..."
268,20260207_190503,2026-02-07 19:12:00,decision_tree_classifier,multi_class_classification,full,non_grid,True,none,StandardScaler,0,0.031307,1,"[{'Bankrupt': 196, 'Flop': 138, 'Huge Success'..."
269,20260207_190503,2026-02-07 19:13:21,lightgbm_regressor,regression,full,non_grid,True,complex,StandardScaler,0,1.126410,1,None
270,20260207_190503,2026-02-07 19:12:37,random_forest_classifier,multi_class_classification,small_productions,non_grid,True,none,StandardScaler,0,0.165857,1,"[{'Bankrupt': 86, 'Flop': 24, 'Huge Success': ..."
271,20260207_190503,2026-02-07 19:06:26,xgboost_classifier,binary_classification,full,non_grid,True,complex,StandardScaler,0,3.403483,1,"[{'0': 641, '1': 191}, {'0': 206, '1': 281}]"

In [8]:
experiment_df

,run_id,timestamp,model_type,problem_type,dataset_name,grid_type,has_outliers_removed,feature_engineering,scaler,variance_threshold,duration,number_of_combinations,ROC AUC Score,Accuracy,Precision,Recall,F1 Score,MSE,MAPE,MAE,RMSE,RMSLE,MSLE,R2,Threshold Probability Accuracy,Threshold Probability Accuracy (log10),Threshold MAPE,Threshold MAPE (25%),predicted_vs_actual
0,20260207_190503,2026-02-07 19:10:52,random_forest_classifier,binary_classification,full,non_grid,False,none,StandardScaler,0,0.989376,1,0.794018,0.725587,0.605477,0.683066,0.641935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20260207_190503,2026-02-07 19:10:45,decision_tree_classifier,binary_classification,large_productions,non_grid,True,none,StandardScaler,0,0.019991,1,0.674932,0.587896,0.473799,0.828244,0.602778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20260207_190503,2026-02-07 19:12:56,xgboost_classifier,binary_classification,large_productions,non_grid,True,complex,StandardScaler,0,2.880083,1,0.764481,0.698847,0.607287,0.572519,0.589391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20260207_190503,2026-02-07 19:11:19,logistic_regression,multi_class_classification,small_productions,non_grid,False,none,StandardScaler,0,0.113967,1,NaN,0.462031,0.578943,0.462031,0.506938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20260207_190503,2026-02-07 19:06:30,lightgbm_regressor,regression,small_productions,non_grid,True,none,StandardScaler,0,0.466886,1,NaN,NaN,NaN,NaN,NaN,1.385934e+14,1.452406,7.375447e+06,1.177257e+07,1.174062,1.378422,0.079762,0.135977,0.254958,1.559430,1.719170,"""{\""movie_id\"":{\""count\"":353.0,\""mean\"":80064..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,20260207_190503,2026-02-07 19:09:25,decision_tree_classifier,multi_class_classification,medium_productions,non_grid,True,complex,StandardScaler,0,0.070245,1,NaN,0.249084,0.362873,0.249084,0.276194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,20260207_190503,2026-02-07 19:12:00,decision_tree_classifier,multi_class_classification,full,non_grid,True,none,StandardScaler,0,0.031307,1,NaN,0.339651,0.455084,0.339651,0.376542,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,20260207_190503,2026-02-07 19:13:21,lightgbm_regressor,regression,full,non_grid,True,complex,StandardScaler,0,1.126410,1,NaN,NaN,NaN,NaN,NaN,9.007343e+15,0.992572,4.368845e+07,9.490702e+07,0.919227,0.844979,0.679463,0.184989,0.330553,1.089634,1.247723,"""{\""movie_id\"":{\""count\"":1319.0,\""mean\"":6571..."
270,20260207_190503,2026-02-07 19:12:37,random_forest_classifier,multi_class_classification,small_productions,non_grid,True,none,StandardScaler,0,0.165857,1,NaN,0.396601,0.389905,0.396601,0.392578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,20260207_190503,2026-02-07 19:06:26,xgboost_classifier,binary_classification,full,non_grid,True,complex,StandardScaler,0,3.403483,1,0.752949,0.699014,0.595339,0.577002,0.586027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
experiment_df.groupby("run_id").aggregate(
    {
        "run_id": "count",
        "dataset_name": "nunique",
        "model_type": "nunique",
        "timestamp": "max",
        "duration": "sum"
    }
).rename(columns={"run_id": "count"}).sort_values("timestamp", ascending=False)

,count,dataset_name,model_type,timestamp,duration
run_id,,,,,
20260207_190503,272,4,11,2026-02-07 19:13:54,518.237494

In [10]:
parameters_df = parameters_df[parameters_df["run_id"].isin(RUNS_IDS)]
experiment_df = experiment_df[experiment_df["run_id"].isin(RUNS_IDS)]
conf_matrix_df = conf_matrix_df[conf_matrix_df["run_id"].isin(RUNS_IDS)]

In [11]:
parameters_df[
    [
        "problem_type",
        "dataset_name",
        "has_outliers_removed",
        "feature_engineering",
        "model_type",
        "scaler",
        "variance_threshold",
        "class_weight",
        "C",
        "min_child_samples",
        "solver",
        "num_leaves",
        "n_estimators",
    ]
].sort_values(by=["model_type", "problem_type", "dataset_name", "has_outliers_removed"])

,problem_type,dataset_name,has_outliers_removed,feature_engineering,model_type,scaler,variance_threshold,class_weight,C,min_child_samples,solver,num_leaves,n_estimators
180,binary_classification,full,False,none,decision_tree_classifier,StandardScaler,0,"{'0': 0.7811946546449847, '1': 1.3890638419696...",NaN,NaN,NaN,NaN,NaN
206,binary_classification,full,False,complex,decision_tree_classifier,StandardScaler,0,"{'0': 0.7811946546449847, '1': 1.3890638419696...",NaN,NaN,NaN,NaN,NaN
148,binary_classification,full,True,complex,decision_tree_classifier,StandardScaler,0,"{'0': 0.7926682692307693, '1': 1.3542094455852...",NaN,NaN,NaN,NaN,NaN
156,binary_classification,full,True,none,decision_tree_classifier,StandardScaler,0,"{'0': 0.7926682692307693, '1': 1.3542094455852...",NaN,NaN,NaN,NaN,NaN
17,binary_classification,large_productions,False,none,decision_tree_classifier,StandardScaler,0,"{'0': 0.8155757286192069, '1': 1.2922028766086...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,regression,medium_productions,True,complex,xgboost_regressor,StandardScaler,0,NaN,NaN,NaN,NaN,NaN,293.0
79,regression,small_productions,False,none,xgboost_regressor,StandardScaler,0,NaN,NaN,NaN,NaN,NaN,293.0
124,regression,small_productions,False,complex,xgboost_regressor,StandardScaler,0,NaN,NaN,NaN,NaN,NaN,293.0
98,regression,small_productions,True,complex,xgboost_regressor,StandardScaler,0,NaN,NaN,NaN,NaN,NaN,293.0
146,regression,small_productions,True,none,xgboost_regressor,StandardScaler,0,NaN,NaN,NaN,NaN,NaN,293.0

In [12]:
parameters_df[parameters_df["model_type"] == "xgboost_regressor"][
    [
        "timestamp",
        "problem_type",
        "dataset_name",
        "has_outliers_removed",
        "feature_engineering",
        "model_type",
        "scaler",
        "variance_threshold",
        "n_estimators",
        "max_depth",
        "learning_rate"
    ]
]

,timestamp,problem_type,dataset_name,has_outliers_removed,feature_engineering,model_type,scaler,variance_threshold,n_estimators,max_depth,learning_rate
13,2026-02-07 19:05:56,regression,large_productions,False,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
14,2026-02-07 19:13:20,regression,full,True,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
43,2026-02-07 19:11:53,regression,full,False,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
58,2026-02-07 19:12:59,regression,full,True,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
61,2026-02-07 19:09:32,regression,medium_productions,True,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
79,2026-02-07 19:05:38,regression,small_productions,False,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
98,2026-02-07 19:10:50,regression,small_productions,True,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
107,2026-02-07 19:13:14,regression,full,False,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
124,2026-02-07 19:11:14,regression,small_productions,False,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
129,2026-02-07 19:13:22,regression,large_productions,False,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
146,2026-02-07 19:06:29,regression,small_productions,True,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
165,2026-02-07 19:12:36,regression,medium_productions,False,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
209,2026-02-07 19:11:59,regression,large_productions,True,none,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
216,2026-02-07 19:11:18,regression,large_productions,True,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
241,2026-02-07 19:11:51,regression,medium_productions,False,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378
264,2026-02-07 19:11:58,regression,medium_productions,True,complex,xgboost_regressor,StandardScaler,0,293.0,6.0,0.108378

In [13]:
display(experiment_df.sort_values(by="timestamp", ascending=True).tail(10))

,run_id,timestamp,model_type,problem_type,dataset_name,grid_type,has_outliers_removed,feature_engineering,scaler,variance_threshold,duration,number_of_combinations,ROC AUC Score,Accuracy,Precision,Recall,F1 Score,MSE,MAPE,MAE,RMSE,RMSLE,MSLE,R2,Threshold Probability Accuracy,Threshold Probability Accuracy (log10),Threshold MAPE,Threshold MAPE (25%),predicted_vs_actual
248,20260207_190503,2026-02-07 19:13:24,logistic_regression,multi_class_classification,full,non_grid,False,none,StandardScaler,0,0.642449,1,NaN,0.452822,0.549001,0.452822,0.488073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,20260207_190503,2026-02-07 19:13:24,random_forest_classifier,multi_class_classification,full,non_grid,False,none,StandardScaler,0,0.297516,1,NaN,0.540585,0.567945,0.540585,0.553197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,20260207_190503,2026-02-07 19:13:28,xgboost_classifier,multi_class_classification,full,non_grid,False,none,StandardScaler,0,4.245578,1,NaN,0.567367,0.508741,0.567367,0.532463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,20260207_190503,2026-02-07 19:13:51,random_forest_classifier,binary_classification,small_productions,non_grid,True,none,StandardScaler,0,0.305542,1,0.626986,0.623229,0.492754,0.519084,0.505576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,20260207_190503,2026-02-07 19:13:51,lightgbm_classifier,multi_class_classification,full,non_grid,False,none,StandardScaler,0,22.288059,1,NaN,0.555418,0.530743,0.555418,0.542014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,20260207_190503,2026-02-07 19:13:51,dummy_classifier,binary_classification,small_productions,non_grid,True,none,StandardScaler,0,0.015826,1,0.500000,0.628895,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,20260207_190503,2026-02-07 19:13:51,decision_tree_classifier,binary_classification,small_productions,non_grid,True,none,StandardScaler,0,0.015649,1,0.602142,0.626062,0.496000,0.473282,0.484375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,20260207_190503,2026-02-07 19:13:51,logistic_regression,binary_classification,small_productions,non_grid,True,none,StandardScaler,0,0.020554,1,0.584485,0.560907,0.425926,0.526718,0.470990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,20260207_190503,2026-02-07 19:13:53,xgboost_classifier,binary_classification,small_productions,non_grid,True,none,StandardScaler,0,1.899640,1,0.605632,0.606232,0.470149,0.480916,0.475472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,20260207_190503,2026-02-07 19:13:54,lightgbm_classifier,binary_classification,small_productions,non_grid,True,none,StandardScaler,0,0.984326,1,0.622619,0.620397,0.490683,0.603053,0.541096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
problem_types = ["regression", "binary_classification", "multi_class_classification"]
groupby_columns = ["dataset_name", "has_outliers_removed", "feature_engineering"]
metrics = {
    "regression": {"metric": "MAPE", "operation": "min"},
    "binary_classification": {"metric": "F1 Score", "operation": "max"},
    "multi_class_classification": {"metric": "F1 Score", "operation": "max"},
}
display_columns = {
    "regression": [
        "model_type",
        "scaler",
        "MAPE",
        "Threshold Probability Accuracy",
        "R2",
        "duration",
    ],
    "binary_classification": ["model_type", "scaler", "F1 Score", 
                              "Accuracy","Precision","Recall",
                              "duration"],
    "multi_class_classification": ["model_type", "scaler", "F1 Score", 
                                   "Accuracy","Precision","Recall",
                                   "duration"],
}

best_models = select_best_models(
    experiment_df, problem_types, groupby_columns, metrics, display_columns
)

# Access results
result_reg = best_models["regression"]
result_class = best_models["binary_classification"]
result_multi_class = best_models["multi_class_classification"]

In [15]:
print(
    result_reg.to_string(
        index=False, justify="center", float_format="%.2f", decimal="."
    )
)

problem_type    dataset_name     has_outliers_removed feature_engineering        model_type           scaler      MAPE   Threshold Probability Accuracy  R2   duration
 regression                full         False               complex            lightgbm_regressor StandardScaler 512.78               0.14              0.47    2.98
 regression                full         False                  none       decision_tree_regressor StandardScaler 548.36               0.12              0.44    0.05
 regression                full          True               complex             xgboost_regressor StandardScaler   0.95               0.19              0.68    0.72
 regression                full          True                  none       random_forest_regressor StandardScaler   1.05               0.16              0.72    0.23
 regression   large_productions         False               complex             xgboost_regressor StandardScaler   1.07               0.20              0.64    0.66
 regression   large_productions         False                  none       random_forest_regressor StandardScaler   1.24               0.17              0.58    0.18
 regression   large_productions          True               complex             xgboost_regressor StandardScaler   0.89               0.21              0.66    0.64
 regression   large_productions          True                  none            lightgbm_regressor StandardScaler   1.06               0.19              0.59    0.44
 regression  medium_productions         False               complex       decision_tree_regressor StandardScaler  24.28               0.12              0.33    0.09
 regression  medium_productions         False                  none             xgboost_regressor StandardScaler  90.87               0.11              0.20    0.36
 regression  medium_productions          True               complex             xgboost_regressor StandardScaler   1.20               0.16              0.17    0.46
 regression  medium_productions          True                  none       random_forest_regressor StandardScaler   1.27               0.14              0.10    0.10
 regression   small_productions         False               complex            lightgbm_regressor StandardScaler 121.31               0.09              0.06    1.93
 regression   small_productions         False                  none             xgboost_regressor StandardScaler 195.57               0.11              0.15    0.38
 regression   small_productions          True               complex             xgboost_regressor StandardScaler   1.32               0.14              0.15    0.58
 regression   small_productions          True                  none       random_forest_regressor StandardScaler   1.34               0.12              0.11    0.12

In [16]:
print(
    result_class.to_string(
        index=False, justify="center", float_format="%.2f", decimal="."
    )
)

     problem_type        dataset_name     has_outliers_removed feature_engineering        model_type            scaler      F1 Score  Accuracy  Precision  Recall  duration
binary_classification               full         False               complex            lightgbm_classifier StandardScaler    0.68      0.75      0.63      0.73     2.51
binary_classification               full         False                  none            lightgbm_classifier StandardScaler    0.65      0.72      0.59      0.73     2.13
binary_classification               full          True               complex            logistic_regression StandardScaler    0.62      0.70      0.59      0.65     7.51
binary_classification               full          True                  none            lightgbm_classifier StandardScaler    0.58      0.66      0.53      0.64     2.00
binary_classification  large_productions         False               complex             xgboost_classifier StandardScaler    0.69      0.75      0.66      0.73     3.14
binary_classification  large_productions         False                  none            logistic_regression StandardScaler    0.67      0.70      0.59      0.79     0.13
binary_classification  large_productions          True               complex            logistic_regression StandardScaler    0.62      0.69      0.57      0.68     3.44
binary_classification  large_productions          True                  none       decision_tree_classifier StandardScaler    0.60      0.59      0.47      0.83     0.02
binary_classification medium_productions         False               complex            lightgbm_classifier StandardScaler    0.61      0.74      0.58      0.63     1.43
binary_classification medium_productions         False                  none            lightgbm_classifier StandardScaler    0.61      0.73      0.55      0.68     1.28
binary_classification medium_productions          True               complex            logistic_regression StandardScaler    0.59      0.66      0.51      0.70     1.32
binary_classification medium_productions          True                  none            logistic_regression StandardScaler    0.58      0.64      0.49      0.71     0.02
binary_classification  small_productions         False               complex            lightgbm_classifier StandardScaler    0.66      0.74      0.63      0.69     2.29
binary_classification  small_productions         False                  none            lightgbm_classifier StandardScaler    0.62      0.70      0.58      0.67     2.00
binary_classification  small_productions          True               complex            logistic_regression StandardScaler    0.51      0.61      0.47      0.56     1.81
binary_classification  small_productions          True                  none            lightgbm_classifier StandardScaler    0.54      0.62      0.49      0.60     0.98

In [17]:
print(
    result_multi_class.to_string(
        index=False, justify="center", float_format="%.2f", decimal="."
    )
)

       problem_type           dataset_name     has_outliers_removed feature_engineering        model_type            scaler      F1 Score  Accuracy  Precision  Recall  duration
multi_class_classification               full         False               complex            lightgbm_classifier StandardScaler    0.58      0.62      0.56      0.62    17.37
multi_class_classification               full         False                  none       random_forest_classifier StandardScaler    0.55      0.54      0.57      0.54     0.30
multi_class_classification               full          True               complex            lightgbm_classifier StandardScaler    0.48      0.51      0.45      0.51    11.90
multi_class_classification               full          True                  none       random_forest_classifier StandardScaler    0.47      0.49      0.46      0.49     0.23
multi_class_classification  large_productions         False               complex            lightgbm_classifier StandardScaler    0.54      0.57      0.51      0.57     7.77
multi_class_classification  large_productions         False                  none       random_forest_classifier StandardScaler    0.51      0.51      0.50      0.51     0.19
multi_class_classification  large_productions          True               complex             xgboost_classifier StandardScaler    0.47      0.51      0.45      0.51     4.67
multi_class_classification  large_productions          True                  none       random_forest_classifier StandardScaler    0.44      0.45      0.44      0.45     0.19
multi_class_classification medium_productions         False               complex             xgboost_classifier StandardScaler    0.59      0.64      0.57      0.64     3.76
multi_class_classification medium_productions         False                  none            lightgbm_classifier StandardScaler    0.52      0.53      0.51      0.53     6.16
multi_class_classification medium_productions          True               complex             xgboost_classifier StandardScaler    0.48      0.52      0.46      0.52     3.09
multi_class_classification medium_productions          True                  none       random_forest_classifier StandardScaler    0.44      0.43      0.44      0.43     0.17
multi_class_classification  small_productions         False               complex       random_forest_classifier StandardScaler    0.60      0.62      0.58      0.62     0.38
multi_class_classification  small_productions         False                  none             xgboost_classifier StandardScaler    0.55      0.58      0.54      0.58     4.08
multi_class_classification  small_productions          True               complex            lightgbm_classifier StandardScaler    0.41      0.44      0.44      0.44     4.25
multi_class_classification  small_productions          True                  none       random_forest_classifier StandardScaler    0.39      0.40      0.39      0.40     0.17

In [18]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df,
    problem_type="binary_classification",
    metric="F1 Score",
    metric_agg="max",
    print_stats=True,
    filename_prefix="step_4",
)

          dataset_name  has_outliers_removed feature_engineering  F1 Score
0                 full                 False             complex  0.680128
1                 full                 False                none  0.653689
2                 full                  True             complex  0.617476
3                 full                  True                none  0.582868
4    large_productions                 False             complex  0.694524
5    large_productions                 False                none  0.672680
6    large_productions                  True             complex  0.621053
7    large_productions                  True                none  0.602778
8   medium_productions                 False             complex  0.605678
9   medium_productions                 False                none  0.611765
10  medium_productions                  True             complex  0.589286
11  medium_productions                  True                none  0.577586
12   small_productions                 False             complex  0.658596
13   small_productions                 False                none  0.619552
14   small_productions                  True             complex  0.512281
15   small_productions                  True                none  0.541096

          dataset_name  has_outliers_removed feature_engineering  F1 Score
0                 full                 False             complex  0.680128
1                 full                 False                none  0.653689
2                 full                  True             complex  0.617476
3                 full                  True                none  0.582868
4    large_productions                 False             complex  0.694524
5    large_productions                 False                none  0.672680
6    large_productions                  True             complex  0.621053
7    large_productions                  True                none  0.602778
8   medium_productions                 False             complex  0.605678
9   medium_productions                 False                none  0.611765
10  medium_productions                  True             complex  0.589286
11  medium_productions                  True                none  0.577586
12   small_productions                 False             complex  0.658596
13   small_productions                 False                none  0.619552
14   small_productions                  True             complex  0.512281
15   small_productions                  True                none  0.541096

In [19]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df,
    problem_type="multi_class_classification",
    metric="F1 Score",
    metric_agg="max",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering  F1 Score
0                 full                 False             complex  0.579248
1                 full                 False                none  0.553197
2                 full                  True             complex  0.478513
3                 full                  True                none  0.471713
4    large_productions                 False             complex  0.536695
5    large_productions                 False                none  0.505004
6    large_productions                  True             complex  0.469720
7    large_productions                  True                none  0.441985
8   medium_productions                 False             complex  0.593114
9   medium_productions                 False                none  0.519866
10  medium_productions                  True             complex  0.476568
11  medium_productions                  True                none  0.435021
12   small_productions                 False             complex  0.595029
13   small_productions                 False                none  0.552705
14   small_productions                  True             complex  0.414545
15   small_productions                  True                none  0.392578

          dataset_name  has_outliers_removed feature_engineering  F1 Score
0                 full                 False             complex  0.579248
1                 full                 False                none  0.553197
2                 full                  True             complex  0.478513
3                 full                  True                none  0.471713
4    large_productions                 False             complex  0.536695
5    large_productions                 False                none  0.505004
6    large_productions                  True             complex  0.469720
7    large_productions                  True                none  0.441985
8   medium_productions                 False             complex  0.593114
9   medium_productions                 False                none  0.519866
10  medium_productions                  True             complex  0.476568
11  medium_productions                  True                none  0.435021
12   small_productions                 False             complex  0.595029
13   small_productions                 False                none  0.552705
14   small_productions                  True             complex  0.414545
15   small_productions                  True                none  0.392578

In [20]:

plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df, problem_type="regression", metric="Threshold MAPE", metric_agg="min",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering  \
0                 full                 False             complex
1                 full                 False                none
2                 full                  True             complex
3                 full                  True                none
4    large_productions                 False             complex
5    large_productions                 False                none
6    large_productions                  True             complex
7    large_productions                  True                none
8   medium_productions                 False             complex
9   medium_productions                 False                none
10  medium_productions                  True             complex
11  medium_productions                  True                none
12   small_productions                 False             complex
13   small_productions                 False                none
14   small_productions                  True             complex
15   small_productions                  True                none

    Threshold MAPE
0       548.964986
1       582.693226
2         1.048549
3         1.136082
4         1.195365
5         1.344253
6         1.000664
7         1.162864
8        25.781167
9        95.011055
10        1.302326
11        1.322747
12      126.280094
13      209.972237
14        1.413628
15        1.411443

,dataset_name,has_outliers_removed,feature_engineering,Threshold MAPE
0,full,False,complex,548.964986
1,full,False,none,582.693226
2,full,True,complex,1.048549
3,full,True,none,1.136082
4,large_productions,False,complex,1.195365
5,large_productions,False,none,1.344253
6,large_productions,True,complex,1.000664
7,large_productions,True,none,1.162864
8,medium_productions,False,complex,25.781167
9,medium_productions,False,none,95.011055
10,medium_productions,True,complex,1.302326
11,medium_productions,True,none,1.322747
12,small_productions,False,complex,126.280094
13,small_productions,False,none,209.972237
14,small_productions,True,complex,1.413628
15,small_productions,True,none,1.411443

In [29]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df, problem_type="regression", metric="Threshold Probability Accuracy (log10)", metric_agg="max",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering  \
0                 full                 False             complex
1                 full                 False                none
2                 full                  True             complex
3                 full                  True                none
4    large_productions                 False             complex
5    large_productions                 False                none
6    large_productions                  True             complex
7    large_productions                  True                none
8   medium_productions                 False             complex
9   medium_productions                 False                none
10  medium_productions                  True             complex
11  medium_productions                  True                none
12   small_productions                 False             complex
13   small_productions                 False                none
14   small_productions                  True             complex
15   small_productions                  True                none

    Threshold Probability Accuracy (log10)
0                                 0.283478
1                                 0.256696
2                                 0.341926
3                                 0.312358
4                                 0.386417
5                                 0.332553
6                                 0.374640
7                                 0.348703
8                                 0.266112
9                                 0.261954
10                                0.329670
11                                0.304029
12                                0.239707
13                                0.219579
14                                0.266289
15                                0.254958

,dataset_name,has_outliers_removed,feature_engineering,Threshold Probability Accuracy (log10)
0,full,False,complex,0.283478
1,full,False,none,0.256696
2,full,True,complex,0.341926
3,full,True,none,0.312358
4,large_productions,False,complex,0.386417
5,large_productions,False,none,0.332553
6,large_productions,True,complex,0.374640
7,large_productions,True,none,0.348703
8,medium_productions,False,complex,0.266112
9,medium_productions,False,none,0.261954
10,medium_productions,True,complex,0.329670
11,medium_productions,True,none,0.304029
12,small_productions,False,complex,0.239707
13,small_productions,False,none,0.219579
14,small_productions,True,complex,0.266289
15,small_productions,True,none,0.254958

In [21]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df, problem_type="regression", metric="MAPE", metric_agg="min",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering        MAPE
0                 full                 False             complex  512.777573
1                 full                 False                none  548.363463
2                 full                  True             complex    0.949916
3                 full                  True                none    1.051810
4    large_productions                 False             complex    1.066680
5    large_productions                 False                none    1.240087
6    large_productions                  True             complex    0.887728
7    large_productions                  True                none    1.059851
8   medium_productions                 False             complex   24.283128
9   medium_productions                 False                none   90.865321
10  medium_productions                  True             complex    1.197312
11  medium_productions                  True                none    1.267222
12   small_productions                 False             complex  121.313836
13   small_productions                 False                none  195.567750
14   small_productions                  True             complex    1.320627
15   small_productions                  True                none    1.342950

          dataset_name  has_outliers_removed feature_engineering        MAPE
0                 full                 False             complex  512.777573
1                 full                 False                none  548.363463
2                 full                  True             complex    0.949916
3                 full                  True                none    1.051810
4    large_productions                 False             complex    1.066680
5    large_productions                 False                none    1.240087
6    large_productions                  True             complex    0.887728
7    large_productions                  True                none    1.059851
8   medium_productions                 False             complex   24.283128
9   medium_productions                 False                none   90.865321
10  medium_productions                  True             complex    1.197312
11  medium_productions                  True                none    1.267222
12   small_productions                 False             complex  121.313836
13   small_productions                 False                none  195.567750
14   small_productions                  True             complex    1.320627
15   small_productions                  True                none    1.342950

In [22]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df, problem_type="regression", metric="R2", metric_agg="max",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering        R2
0                 full                 False             complex  0.546605
1                 full                 False                none  0.512143
2                 full                  True             complex  0.701627
3                 full                  True                none  0.719509
4    large_productions                 False             complex  0.640492
5    large_productions                 False                none  0.576774
6    large_productions                  True             complex  0.664263
7    large_productions                  True                none  0.648979
8   medium_productions                 False             complex  0.334785
9   medium_productions                 False                none  0.371819
10  medium_productions                  True             complex  0.174723
11  medium_productions                  True                none  0.166483
12   small_productions                 False             complex  0.177901
13   small_productions                 False                none  0.179679
14   small_productions                  True             complex  0.146700
15   small_productions                  True                none  0.110380

          dataset_name  has_outliers_removed feature_engineering        R2
0                 full                 False             complex  0.546605
1                 full                 False                none  0.512143
2                 full                  True             complex  0.701627
3                 full                  True                none  0.719509
4    large_productions                 False             complex  0.640492
5    large_productions                 False                none  0.576774
6    large_productions                  True             complex  0.664263
7    large_productions                  True                none  0.648979
8   medium_productions                 False             complex  0.334785
9   medium_productions                 False                none  0.371819
10  medium_productions                  True             complex  0.174723
11  medium_productions                  True                none  0.166483
12   small_productions                 False             complex  0.177901
13   small_productions                 False                none  0.179679
14   small_productions                  True             complex  0.146700
15   small_productions                  True                none  0.110380

In [23]:
plot_one_metric_of_different_models_per_dataset_with_plotly(
    experiment_df,
    problem_type="regression",
    metric="R2",
    metric_agg="max",
    benchmark_model="dummy_regressor",
    print_stats=True,
        filename_prefix="step_4"

)

         dataset_name feature_engineering  has_outliers_removed  \
0                full             complex                 False
1                full             complex                 False
2                full             complex                 False
3                full             complex                 False
4                full             complex                 False
..                ...                 ...                   ...
75  small_productions                none                  True
76  small_productions                none                  True
77  small_productions                none                  True
78  small_productions                none                  True
79  small_productions                none                  True

                 model_type        R2          group
0   decision_tree_regressor  0.425907  complex_False
1           dummy_regressor -0.106638  complex_False
2        lightgbm_regressor  0.468805  complex_False
3   random_forest_regressor  0.491246  complex_False
4         xgboost_regressor  0.546605  complex_False
..                      ...       ...            ...
75  decision_tree_regressor  0.079225      none_True
76          dummy_regressor -0.206377      none_True
77       lightgbm_regressor  0.079762      none_True
78  random_forest_regressor  0.110380      none_True
79        xgboost_regressor  0.098736      none_True

[80 rows x 6 columns]

,dataset_name,feature_engineering,has_outliers_removed,model_type,R2,group
0,full,complex,False,decision_tree_regressor,0.425907,complex_False
1,full,complex,False,dummy_regressor,-0.106638,complex_False
2,full,complex,False,lightgbm_regressor,0.468805,complex_False
3,full,complex,False,random_forest_regressor,0.491246,complex_False
4,full,complex,False,xgboost_regressor,0.546605,complex_False
...,...,...,...,...,...,...
75,small_productions,none,True,decision_tree_regressor,0.079225,none_True
76,small_productions,none,True,dummy_regressor,-0.206377,none_True
77,small_productions,none,True,lightgbm_regressor,0.079762,none_True
78,small_productions,none,True,random_forest_regressor,0.110380,none_True
79,small_productions,none,True,xgboost_regressor,0.098736,none_True

In [24]:
plot_one_metric_of_different_models_per_dataset_with_plotly(
    experiment_df,
    problem_type="regression",
    metric="MAPE",
    metric_agg="min",
    benchmark_model="dummy_regressor",
    print_stats=True,
        filename_prefix="step_4"

)

         dataset_name feature_engineering  has_outliers_removed  \
0                full             complex                 False
1                full             complex                 False
2                full             complex                 False
3                full             complex                 False
4                full             complex                 False
..                ...                 ...                   ...
75  small_productions                none                  True
76  small_productions                none                  True
77  small_productions                none                  True
78  small_productions                none                  True
79  small_productions                none                  True

                 model_type          MAPE          group
0   decision_tree_regressor   1080.648051  complex_False
1           dummy_regressor  36707.197287  complex_False
2        lightgbm_regressor    512.777573  complex_False
3   random_forest_regressor    773.790431  complex_False
4         xgboost_regressor    939.752874  complex_False
..                      ...           ...            ...
75  decision_tree_regressor      1.461933      none_True
76          dummy_regressor      2.422195      none_True
77       lightgbm_regressor      1.452406      none_True
78  random_forest_regressor      1.342950      none_True
79        xgboost_regressor      1.455166      none_True

[80 rows x 6 columns]

,dataset_name,feature_engineering,has_outliers_removed,model_type,MAPE,group
0,full,complex,False,decision_tree_regressor,1080.648051,complex_False
1,full,complex,False,dummy_regressor,36707.197287,complex_False
2,full,complex,False,lightgbm_regressor,512.777573,complex_False
3,full,complex,False,random_forest_regressor,773.790431,complex_False
4,full,complex,False,xgboost_regressor,939.752874,complex_False
...,...,...,...,...,...,...
75,small_productions,none,True,decision_tree_regressor,1.461933,none_True
76,small_productions,none,True,dummy_regressor,2.422195,none_True
77,small_productions,none,True,lightgbm_regressor,1.452406,none_True
78,small_productions,none,True,random_forest_regressor,1.342950,none_True
79,small_productions,none,True,xgboost_regressor,1.455166,none_True

In [25]:
plot_one_metric_of_different_models_per_dataset_with_plotly(
    experiment_df,
    problem_type="binary_classification",
    metric="F1 Score",
    metric_agg="max",
    benchmark_model="dummy_classifier",
    print_stats=True,
        filename_prefix="step_4"

)

         dataset_name feature_engineering  has_outliers_removed  \
0                full             complex                 False
1                full             complex                 False
2                full             complex                 False
3                full             complex                 False
4                full             complex                 False
..                ...                 ...                   ...
91  small_productions                none                  True
92  small_productions                none                  True
93  small_productions                none                  True
94  small_productions                none                  True
95  small_productions                none                  True

                  model_type  F1 Score          group
0   decision_tree_classifier  0.606789  complex_False
1           dummy_classifier  0.000000  complex_False
2        lightgbm_classifier  0.680128  complex_False
3        logistic_regression  0.645866  complex_False
4   random_forest_classifier  0.649173  complex_False
..                       ...       ...            ...
91          dummy_classifier  0.000000      none_True
92       lightgbm_classifier  0.541096      none_True
93       logistic_regression  0.470990      none_True
94  random_forest_classifier  0.505576      none_True
95        xgboost_classifier  0.475472      none_True

[96 rows x 6 columns]

,dataset_name,feature_engineering,has_outliers_removed,model_type,F1 Score,group
0,full,complex,False,decision_tree_classifier,0.606789,complex_False
1,full,complex,False,dummy_classifier,0.000000,complex_False
2,full,complex,False,lightgbm_classifier,0.680128,complex_False
3,full,complex,False,logistic_regression,0.645866,complex_False
4,full,complex,False,random_forest_classifier,0.649173,complex_False
...,...,...,...,...,...,...
91,small_productions,none,True,dummy_classifier,0.000000,none_True
92,small_productions,none,True,lightgbm_classifier,0.541096,none_True
93,small_productions,none,True,logistic_regression,0.470990,none_True
94,small_productions,none,True,random_forest_classifier,0.505576,none_True
95,small_productions,none,True,xgboost_classifier,0.475472,none_True

In [26]:
# Load the data

# Example usage
problem_types = ["binary_classification", "multi_class_classification"]
groupby_columns = ["dataset_name", "has_outliers_removed", "feature_engineering"]
metrics = {
    "binary_classification": {"metric": "F1 Score", "operation": "max"},
    "multi_class_classification": {"metric": "F1 Score", "operation": "max"},
}

plot_best_confusion_matrices_from_metadata(
    experiment_df=experiment_df,
    conf_matrix_df=conf_matrix_df,
    problem_types=problem_types,
    groupby_columns=groupby_columns,
    metrics=metrics,
    display_chart=True,
    print_stats=True,
    filename_prefix="step_4"
)

Processing binary_classification...

Confusion Matrix:
          Bankrupt  Success
Bankrupt    1185.0    368.0
Success      234.0    640.0

Total samples: 2427

Confusion Matrix:
          Bankrupt  Success
Bankrupt    1113.0    440.0
Success      236.0    638.0

Total samples: 2427

Confusion Matrix:
          Bankrupt  Success
Bankrupt     607.0    225.0
Success      169.0    318.0

Total samples: 1319

Confusion Matrix:
          Bankrupt  Success
Bankrupt     558.0    274.0
Success      174.0    313.0

Total samples: 1319

Confusion Matrix:
          Bankrupt  Success
Bankrupt     401.0    122.0
Success       90.0    241.0

Total samples: 854

Confusion Matrix:
          Bankrupt  Success
Bankrupt     339.0    184.0
Success       70.0    261.0

Total samples: 854

Confusion Matrix:
          Bankrupt  Success
Bankrupt     301.0    131.0
Success       85.0    177.0

Total samples: 694

Confusion Matrix:
          Bankrupt  Success
Bankrupt     191.0    241.0
Success       45.0    217.0

Total samples: 694

Confusion Matrix:
          Bankrupt  Success
Bankrupt     260.0     69.0
Success       56.0     96.0

Total samples: 481

Confusion Matrix:
          Bankrupt  Success
Bankrupt     245.0     84.0
Success       48.0    104.0

Total samples: 481

Confusion Matrix:
          Bankrupt  Success
Bankrupt     115.0     64.0
Success       28.0     66.0

Total samples: 273

Confusion Matrix:
          Bankrupt  Success
Bankrupt     108.0     71.0
Success       27.0     67.0

Total samples: 273

Confusion Matrix:
          Bankrupt  Success
Bankrupt     539.0    162.0
Success      120.0    272.0

Total samples: 1093

Confusion Matrix:
          Bankrupt  Success
Bankrupt     507.0    194.0
Success      129.0    263.0

Total samples: 1093

Confusion Matrix:
          Bankrupt  Success
Bankrupt     141.0     81.0
Success       58.0     73.0

Total samples: 353

Confusion Matrix:
          Bankrupt  Success
Bankrupt     140.0     82.0
Success       52.0     79.0

Total samples: 353

Processing multi_class_classification...

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          888.0  55.0         182.0            2.0
Flop              164.0  46.0         146.0            4.0
Huge Success      184.0  55.0         563.0            4.0
Small Success      52.0  16.0          66.0            0.0

Total samples: 2427

Confusion Matrix:
               Bankrupt   Flop  Huge Success  Small Success
Bankrupt          750.0  159.0         152.0           66.0
Flop              121.0   87.0         104.0           48.0
Huge Success      145.0  139.0         456.0           66.0
Small Success      36.0   38.0          41.0           19.0

Total samples: 2427

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          380.0  47.0         101.0            1.0
Flop              128.0  37.0          88.0            3.0
Huge Success      114.0  55.0         262.0            7.0
Small Success      23.0  16.0          57.0            0.0

Total samples: 1319

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          339.0  53.0         110.0           27.0
Flop              104.0  41.0          85.0           26.0
Huge Success       99.0  67.0         251.0           21.0
Small Success      26.0  10.0          50.0           10.0

Total samples: 1319

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          250.0  30.0          52.0            5.0
Flop               76.0  22.0          54.0            2.0
Huge Success       47.0  33.0         217.0            3.0
Small Success      19.0   9.0          34.0            1.0

Total samples: 854

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          209.0  51.0          54.0           23.0
Flop               60.0  28.0          42.0           24.0
Huge Success       47.0  37.0         189.0           27.0
Small Success      21.0  13.0          23.0            6.0

Total samples: 854

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          179.0  27.0          54.0            2.0
Flop               60.0  16.0          61.0            3.0
Huge Success       48.0  22.0         159.0            4.0
Small Success      17.0  10.0          31.0            1.0

Total samples: 694

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          155.0  33.0          51.0           23.0
Flop               40.0  18.0          65.0           17.0
Huge Success       44.0  28.0         140.0           21.0
Small Success      17.0  12.0          28.0            2.0

Total samples: 694

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          218.0   8.0          22.0            1.0
Flop               47.0   6.0          16.0            0.0
Huge Success       45.0   6.0          86.0            0.0
Small Success      15.0   1.0          10.0            0.0

Total samples: 481

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          172.0  28.0          42.0            7.0
Flop               38.0   6.0          24.0            1.0
Huge Success       36.0  20.0          75.0            6.0
Small Success       9.0   4.0          11.0            2.0

Total samples: 481

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt           87.0  10.0          19.0            3.0
Flop               26.0   6.0          19.0            0.0
Huge Success       28.0   7.0          48.0            1.0
Small Success      12.0   1.0           6.0            0.0

Total samples: 273

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt           68.0  16.0          22.0           13.0
Flop               18.0  10.0          20.0            3.0
Huge Success       24.0   6.0          39.0           15.0
Small Success       9.0   1.0           8.0            1.0

Total samples: 273

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          424.0  21.0          95.0            2.0
Flop               69.0  23.0          45.0            1.0
Huge Success      108.0  27.0         230.0            4.0
Small Success      14.0  13.0          17.0            0.0

Total samples: 1093

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          402.0  28.0         106.0            6.0
Flop               78.0  15.0          43.0            2.0
Huge Success      125.0  25.0         213.0            6.0
Small Success      18.0   3.0          22.0            1.0

Total samples: 1093

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt           97.0  16.0          36.0            0.0
Flop               31.0   4.0          29.0            0.0
Huge Success       51.0  15.0          55.0            0.0
Small Success       7.0   1.0          10.0            1.0

Total samples: 353

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt           86.0  24.0          36.0            3.0
Flop               29.0   8.0          22.0            5.0
Huge Success       39.0  25.0          46.0           11.0
Small Success       8.0   4.0           7.0            0.0

Total samples: 353

In [27]:
plot_best_regression_results_from_metadata(
    experiment_df=experiment_df,
    display_chart=True,
    print_stats=True,
    filename_prefix="step_4"
)

🔍 Finding best models using MAPE (min)

📈 Found 16 best models:

• Dataset: full
  Model: lightgbm_regressor
  MAPE: 51277.8%
  MAE: $45,073,699
  R²: 0.469

• Dataset: full
  Model: decision_tree_regressor
  MAPE: 54836.3%
  MAE: $45,348,630
  R²: 0.443

• Dataset: full
  Model: xgboost_regressor
  MAPE: 95.0%
  MAE: $43,532,763
  R²: 0.681

• Dataset: full
  Model: random_forest_regressor
  MAPE: 105.2%
  MAE: $44,980,463
  R²: 0.720

• Dataset: large_productions
  Model: xgboost_regressor
  MAPE: 106.7%
  MAE: $81,335,223
  R²: 0.640

• Dataset: large_productions
  Model: random_forest_regressor
  MAPE: 124.0%
  MAE: $92,551,185
  R²: 0.577

• Dataset: large_productions
  Model: xgboost_regressor
  MAPE: 88.8%
  MAE: $68,902,835
  R²: 0.664

• Dataset: large_productions
  Model: lightgbm_regressor
  MAPE: 106.0%
  MAE: $78,207,719
  R²: 0.592

• Dataset: medium_productions
  Model: decision_tree_regressor
  MAPE: 2428.3%
  MAE: $26,876,880
  R²: 0.335

• Dataset: medium_productions
  Model: xgboost_regressor
  MAPE: 9086.5%
  MAE: $27,452,817
  R²: 0.199

• Dataset: medium_productions
  Model: xgboost_regressor
  MAPE: 119.7%
  MAE: $19,631,264
  R²: 0.175

• Dataset: medium_productions
  Model: random_forest_regressor
  MAPE: 126.7%
  MAE: $20,176,530
  R²: 0.095

• Dataset: small_productions
  Model: lightgbm_regressor
  MAPE: 12131.4%
  MAE: $11,885,808
  R²: 0.060

• Dataset: small_productions
  Model: xgboost_regressor
  MAPE: 19556.8%
  MAE: $10,752,636
  R²: 0.150

• Dataset: small_productions
  Model: xgboost_regressor
  MAPE: 132.1%
  MAE: $7,056,307
  R²: 0.147

• Dataset: small_productions
  Model: random_forest_regressor
  MAPE: 134.3%
  MAE: $7,122,574
  R²: 0.110
Saved LaTeX regression results to thesis_assets/tables/table_reg_results_small_productions.tex

📊 Model Performance Summary (Regression):
• Average Error: $7,122,574
• MAPE: 134.30%