In [1]:
import pandas as pd
from eda_support_functions import *

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_info_columns", 1000)

In [3]:
RUNS_IDS = ["20240905_183321","20240905_231518"]

In [4]:
parameters_df = load_metadata(
    "parameters", "/Users/iliasx/Documents/GitHub/box-office-prediction/metadata"
)
experiment_df = load_metadata(
    "metrics", "/Users/iliasx/Documents/GitHub/box-office-prediction/metadata"
)
conf_matrix_df = load_metadata(
    "confusion_matrix", "/Users/iliasx/Documents/GitHub/box-office-prediction/metadata"
)

In [5]:
conf_matrix_df

,run_id,timestamp,model_type,problem_type,dataset_name,grid_type,has_outliers_removed,feature_engineering,scaler,variance_threshold,duration,number_of_combinations,conf_matrix
0,20240905_231518,2024-09-05 23:48:00,dummy_classifier,multi_class_classification,small_productions,random_search,True,complex,RobustScaler,0.159309,1.490351,None,"[{'Bankrupt': 66, 'Flop': 24, 'Huge Success': ..."
1,20240802_224457,2024-08-02 23:24:31,decision_tree_classifier,multi_class_classification,full,random_search,True,none,MinMaxScaler,0.011282,0.115336,None,"[{'Bankrupt': 195, 'Flop': 25, 'Huge Success':..."
2,20240828_231219,2024-08-29 03:08:14,lightgbm_regressor,regression,large_productions,random_search,False,complex,RobustScaler,0.091214,1942.437653,None,None
3,20240905_231518,2024-09-05 23:20:09,dummy_regressor,regression,full,random_search,True,complex,RobustScaler,0.028573,3.854362,None,None
4,20240802_224457,2024-08-02 23:36:14,lightgbm_regressor,regression,full,random_search,True,complex,RobustScaler,0.019995,20.893485,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4114,20240809_224515,2024-08-09 23:26:31,random_forest_regressor,regression,medium_productions,random_search,True,complex,RobustScaler,0.048205,90.286047,None,None
4115,20240808_194937,2024-08-08 19:53:55,xgboost_regressor,regression,large_productions,random_search,False,complex,RobustScaler,0.019995,7.367819,None,None
4116,20240802_224457,2024-08-02 23:15:24,logistic_regression,multi_class_classification,small_productions,random_search,False,none,RobustScaler,0.019995,0.156260,None,"[{'Bankrupt': 72, 'Flop': 0, 'Huge Success': 3..."
4117,20240724_210133,2024-07-24 21:20:18,decision_tree_classifier,multi_class_classification,medium_productions,random_search,False,none,StandardScaler,0.155938,0.783357,None,"[{'Bankrupt': 178, 'Flop': 149, 'Huge Success'..."
4118,20240719_214914,2024-07-19 22:11:33,lightgbm_classifier,binary_classification,large_productions,random_search,True,none,StandardScaler,0.042468,8.073748,None,"[{'0': 157, '1': 91}, {'0': 86, '1': 127}]"

In [6]:
experiment_df

,run_id,timestamp,model_type,problem_type,dataset_name,grid_type,has_outliers_removed,feature_engineering,scaler,variance_threshold,duration,number_of_combinations,Accuracy,Precision,Recall,F1 Score,MSE,MAPE,MAE,RMSE,RMSLE,MSLE,R2,Threshold Probability Accuracy,Threshold MAPE,Threshold MAPE (25%),predicted_vs_actual,ROC AUC Score
0,20240905_231518,2024-09-05 23:48:00,dummy_classifier,multi_class_classification,small_productions,random_search,True,complex,RobustScaler,0.159309,1.490351,None,0.339943,0.333887,0.339943,0.336291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20240802_224457,2024-08-02 23:24:31,decision_tree_classifier,multi_class_classification,full,random_search,True,none,MinMaxScaler,0.011282,0.115336,None,0.498124,0.426014,0.498124,0.452741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20240828_231219,2024-08-29 03:08:14,lightgbm_regressor,regression,large_productions,random_search,False,complex,RobustScaler,0.091214,1942.437653,None,NaN,NaN,NaN,NaN,3.246506e+16,2.011322,8.447956e+07,1.801806e+08,1.047992,1.098288,0.597954,0.160422,2.186235,2.510590,"""{\""movie_id\"":{\""count\"":854.0,\""mean\"":71051...",NaN
3,20240905_231518,2024-09-05 23:20:09,dummy_regressor,regression,full,random_search,True,complex,RobustScaler,0.028573,3.854362,None,NaN,NaN,NaN,NaN,3.161998e+16,5.914191,7.867994e+07,1.778201e+08,1.726922,2.982260,-0.125236,0.088704,6.149837,6.650140,"""{\""movie_id\"":{\""count\"":1319.0,\""mean\"":6571...",NaN
4,20240802_224457,2024-08-02 23:36:14,lightgbm_regressor,regression,full,random_search,True,complex,RobustScaler,0.019995,20.893485,None,NaN,NaN,NaN,NaN,1.372573e+16,1.364065,6.213266e+07,1.171569e+08,1.022013,1.044510,0.656524,0.162289,1.472104,1.679541,"""{\""movie_id\"":{\""count\"":1066.0,\""mean\"":6707...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4114,20240809_224515,2024-08-09 23:26:31,random_forest_regressor,regression,medium_productions,random_search,True,complex,RobustScaler,0.048205,90.286047,None,NaN,NaN,NaN,NaN,4.051588e+15,1.110755,3.805986e+07,6.365209e+07,1.003929,1.007874,0.056268,0.170819,1.192253,1.381440,"""{\""movie_id\"":{\""count\"":281.0,\""mean\"":72212...",NaN
4115,20240808_194937,2024-08-08 19:53:55,xgboost_regressor,regression,large_productions,random_search,False,complex,RobustScaler,0.019995,7.367819,None,NaN,NaN,NaN,NaN,3.397194e+16,2.057118,1.062804e+08,1.843148e+08,1.057773,1.118884,0.579439,0.198934,2.269904,2.718844,"""{\""movie_id\"":{\""count\"":563.0,\""mean\"":55388...",NaN
4116,20240802_224457,2024-08-02 23:15:24,logistic_regression,multi_class_classification,small_productions,random_search,False,none,RobustScaler,0.019995,0.156260,None,0.587189,0.491697,0.587189,0.533433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4117,20240724_210133,2024-07-24 21:20:18,decision_tree_classifier,multi_class_classification,medium_productions,random_search,False,none,StandardScaler,0.155938,0.783357,None,0.335726,0.475243,0.335726,0.381156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4118,20240719_214914,2024-07-19 22:11:33,lightgbm_classifier,binary_classification,large_productions,random_search,True,none,StandardScaler,0.042468,8.073748,None,0.616052,0.582569,0.596244,0.589327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.614654

In [7]:
experiment_df.groupby("run_id").aggregate(
    {
        "run_id": "count",
        "dataset_name": "nunique",
        "model_type": "nunique",
        "timestamp": "max",
        "duration": "sum"
    }
).rename(columns={"run_id": "count"}).sort_values("timestamp", ascending=False)

,count,dataset_name,model_type,timestamp,duration
run_id,,,,,
20240905_231518,56,4,9,2024-09-05 23:49:23,2038.056188
20240905_183321,224,4,9,2024-09-05 20:28:31,6888.694667
20240905_132552,16,4,4,2024-09-05 15:01:36,5741.607827
20240904_111501,3,1,3,2024-09-04 11:19:47,285.314569
20240904_102648,4,1,4,2024-09-04 10:35:57,547.867871
...,...,...,...,...,...
20240719_231427,12,2,6,2024-07-19 23:15:42,72.222618
20240719_225631,2,2,1,2024-07-19 22:58:14,96.393701
20240719_214914,272,4,11,2024-07-19 22:31:25,2467.220396
20240719_214632,6,1,6,2024-07-19 21:47:09,35.216598
20240719_170554,272,4,11,2024-07-19 21:41:48,16494.381705

In [8]:
parameters_df = parameters_df[parameters_df["run_id"].isin(RUNS_IDS)]
experiment_df = experiment_df[experiment_df["run_id"].isin(RUNS_IDS)]
conf_matrix_df = conf_matrix_df[conf_matrix_df["run_id"].isin(RUNS_IDS)]

In [9]:
parameters_df[
    [
        "problem_type",
        "dataset_name",
        "has_outliers_removed",
        "feature_engineering",
        "model_type",
        "scaler",
        "variance_threshold",
        "class_weight",
        "C",
        "min_child_samples",
        "solver",
        "num_leaves",
        "n_estimators",
    ]
].sort_values(by=["model_type", "problem_type", "dataset_name", "has_outliers_removed"])

,problem_type,dataset_name,has_outliers_removed,feature_engineering,model_type,scaler,variance_threshold,class_weight,C,min_child_samples,solver,num_leaves,n_estimators
2158,binary_classification,full,False,complex,decision_tree_classifier,RobustScaler,0.034105,balanced,NaN,NaN,NaN,NaN,NaN
3598,binary_classification,full,False,none,decision_tree_classifier,MinMaxScaler,0.077083,None,NaN,NaN,NaN,NaN,NaN
619,binary_classification,full,True,complex,decision_tree_classifier,MinMaxScaler,0.077083,None,NaN,NaN,NaN,NaN,NaN
961,binary_classification,full,True,complex,decision_tree_classifier,MinMaxScaler,0.077083,None,NaN,NaN,NaN,NaN,NaN
3292,binary_classification,full,True,none,decision_tree_classifier,StandardScaler,0.122331,None,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,regression,small_productions,False,none,xgboost_regressor,StandardScaler,0.146399,NaN,NaN,NaN,NaN,NaN,320.0
748,regression,small_productions,False,complex,xgboost_regressor,MinMaxScaler,0.060848,NaN,NaN,NaN,NaN,NaN,210.0
46,regression,small_productions,True,complex,xgboost_regressor,RobustScaler,0.012712,NaN,NaN,NaN,NaN,NaN,82.0
462,regression,small_productions,True,complex,xgboost_regressor,MinMaxScaler,0.141615,NaN,NaN,NaN,NaN,NaN,921.0
924,regression,small_productions,True,none,xgboost_regressor,StandardScaler,0.146399,NaN,NaN,NaN,NaN,NaN,320.0

In [10]:
parameters_df[parameters_df["model_type"] == "xgboost_regressor"][
    [
        "timestamp",
        "problem_type",
        "dataset_name",
        "has_outliers_removed",
        "feature_engineering",
        "model_type",
        "scaler",
        "variance_threshold",
        "n_estimators",
        "max_depth",
        "learning_rate"
    ]
]

,timestamp,problem_type,dataset_name,has_outliers_removed,feature_engineering,model_type,scaler,variance_threshold,n_estimators,max_depth,learning_rate
46,2024-09-05 23:38:27,regression,small_productions,True,complex,xgboost_regressor,RobustScaler,0.012712,82.0,3.0,0.125660
168,2024-09-05 18:36:34,regression,small_productions,False,none,xgboost_regressor,StandardScaler,0.146399,320.0,30.0,0.075908
378,2024-09-05 20:22:05,regression,full,False,complex,xgboost_regressor,RobustScaler,0.034105,696.0,20.0,0.010290
462,2024-09-05 19:55:08,regression,small_productions,True,complex,xgboost_regressor,MinMaxScaler,0.141615,921.0,5.0,0.174235
696,2024-09-05 20:27:35,regression,large_productions,False,none,xgboost_regressor,StandardScaler,0.076492,612.0,31.0,0.019121
748,2024-09-05 19:59:50,regression,small_productions,False,complex,xgboost_regressor,MinMaxScaler,0.060848,210.0,22.0,0.037365
924,2024-09-05 19:36:22,regression,small_productions,True,none,xgboost_regressor,StandardScaler,0.146399,320.0,30.0,0.075908
1200,2024-09-05 19:34:26,regression,large_productions,False,complex,xgboost_regressor,RobustScaler,0.034105,696.0,20.0,0.010290
1207,2024-09-05 20:27:09,regression,full,True,complex,xgboost_regressor,MinMaxScaler,0.141615,921.0,5.0,0.174235
1375,2024-09-05 23:29:17,regression,full,True,complex,xgboost_regressor,RobustScaler,0.001104,697.0,2.0,0.085680
1568,2024-09-05 20:07:18,regression,full,False,none,xgboost_regressor,StandardScaler,0.146399,320.0,30.0,0.075908
1882,2024-09-05 20:12:04,regression,full,True,none,xgboost_regressor,StandardScaler,0.076492,612.0,31.0,0.019121
2049,2024-09-05 19:49:32,regression,medium_productions,True,none,xgboost_regressor,MinMaxScaler,0.141615,921.0,5.0,0.174235
2132,2024-09-05 20:02:42,regression,large_productions,True,complex,xgboost_regressor,MinMaxScaler,0.141615,921.0,5.0,0.174235
2179,2024-09-05 20:08:46,regression,large_productions,True,none,xgboost_regressor,MinMaxScaler,0.141615,921.0,5.0,0.174235
2567,2024-09-05 23:34:18,regression,large_productions,True,complex,xgboost_regressor,RobustScaler,0.012712,82.0,3.0,0.125660
2677,2024-09-05 23:36:17,regression,medium_productions,True,complex,xgboost_regressor,RobustScaler,0.166639,558.0,13.0,0.137653
2716,2024-09-05 20:06:05,regression,medium_productions,False,complex,xgboost_regressor,RobustScaler,0.019995,516.0,27.0,0.120370
3089,2024-09-05 20:08:28,regression,medium_productions,True,complex,xgboost_regressor,MinMaxScaler,0.112658,365.0,26.0,0.003653
3341,2024-09-05 20:10:31,regression,medium_productions,False,none,xgboost_regressor,StandardScaler,0.076492,612.0,31.0,0.019121

In [11]:
display(experiment_df.sort_values(by="timestamp", ascending=True).tail(10))

,run_id,timestamp,model_type,problem_type,dataset_name,grid_type,has_outliers_removed,feature_engineering,scaler,variance_threshold,duration,number_of_combinations,Accuracy,Precision,Recall,F1 Score,MSE,MAPE,MAE,RMSE,RMSLE,MSLE,R2,Threshold Probability Accuracy,Threshold MAPE,Threshold MAPE (25%),predicted_vs_actual,ROC AUC Score
216,20240905_231518,2024-09-05 23:46:47,dummy_classifier,multi_class_classification,medium_productions,random_search,True,complex,StandardScaler,0.091850,1.429009,None,0.333333,0.343249,0.333333,0.335095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
954,20240905_231518,2024-09-05 23:46:58,logistic_regression,multi_class_classification,medium_productions,random_search,True,complex,StandardScaler,0.113540,11.343416,None,0.542125,0.394434,0.542125,0.456537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,20240905_231518,2024-09-05 23:47:14,random_forest_classifier,multi_class_classification,medium_productions,random_search,True,complex,RobustScaler,0.136847,15.635657,None,0.512821,0.442592,0.512821,0.466150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2738,20240905_231518,2024-09-05 23:47:16,decision_tree_classifier,multi_class_classification,medium_productions,random_search,True,complex,StandardScaler,0.122331,1.558075,None,0.516484,0.377680,0.516484,0.435776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3355,20240905_231518,2024-09-05 23:47:58,xgboost_classifier,multi_class_classification,medium_productions,random_search,True,complex,MinMaxScaler,0.118260,42.514705,None,0.531136,0.446753,0.531136,0.478273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,20240905_231518,2024-09-05 23:48:00,dummy_classifier,multi_class_classification,small_productions,random_search,True,complex,RobustScaler,0.159309,1.490351,None,0.339943,0.333887,0.339943,0.336291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20240905_231518,2024-09-05 23:48:14,logistic_regression,multi_class_classification,small_productions,random_search,True,complex,MinMaxScaler,0.132504,14.591222,None,0.413598,0.351250,0.413598,0.362643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1327,20240905_231518,2024-09-05 23:48:32,random_forest_classifier,multi_class_classification,small_productions,random_search,True,complex,RobustScaler,0.091214,17.567200,None,0.453258,0.341394,0.453258,0.381180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3967,20240905_231518,2024-09-05 23:48:34,decision_tree_classifier,multi_class_classification,small_productions,random_search,True,complex,MinMaxScaler,0.077083,1.666139,None,0.447592,0.369771,0.447592,0.396491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3111,20240905_231518,2024-09-05 23:49:23,xgboost_classifier,multi_class_classification,small_productions,random_search,True,complex,RobustScaler,0.066180,48.929669,None,0.410765,0.360651,0.410765,0.376260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
problem_types = ["regression", "binary_classification", "multi_class_classification"]
groupby_columns = ["dataset_name", "has_outliers_removed", "feature_engineering"]
metrics = {
    "regression": {"metric": "MAPE", "operation": "min"},
    "binary_classification": {"metric": "F1 Score", "operation": "max"},
    "multi_class_classification": {"metric": "F1 Score", "operation": "max"},
}
display_columns = {
    "regression": [
        "model_type",
        "scaler",
        "MAPE",
        "Threshold Probability Accuracy",
        "R2",
        "duration",
    ],
    "binary_classification": ["model_type", "scaler", "F1 Score", 
                              "Accuracy","Precision","Recall",
                              "duration"],
    "multi_class_classification": ["model_type", "scaler", "F1 Score", 
                                   "Accuracy","Precision","Recall",
                                   "duration"],
}

best_models = select_best_models(
    experiment_df, problem_types, groupby_columns, metrics, display_columns
)

# Access results
result_reg = best_models["regression"]
result_class = best_models["binary_classification"]
result_multi_class = best_models["multi_class_classification"]

In [13]:
print(
    result_reg.to_string(
        index=False, justify="center", float_format="%.2f", decimal="."
    )
)

problem_type    dataset_name     has_outliers_removed feature_engineering        model_type           scaler      MAPE   Threshold Probability Accuracy  R2   duration
 regression                full         False               complex             xgboost_regressor   RobustScaler 480.92               0.12              0.49   367.18
 regression                full         False                  none       random_forest_regressor StandardScaler 895.48               0.13              0.51    22.34
 regression                full          True               complex             xgboost_regressor   RobustScaler   0.93               0.17              0.67   243.93
 regression                full          True                  none       random_forest_regressor StandardScaler   1.05               0.16              0.71    11.77
 regression   large_productions         False               complex       random_forest_regressor   MinMaxScaler   1.23               0.19              0.55    69.81
 regression   large_productions         False                  none       random_forest_regressor StandardScaler   1.26               0.18              0.55     7.69
 regression   large_productions          True               complex             xgboost_regressor   RobustScaler   0.94               0.18              0.66   142.80
 regression   large_productions          True                  none       random_forest_regressor   RobustScaler   1.06               0.18              0.65     6.41
 regression  medium_productions         False               complex       decision_tree_regressor StandardScaler  50.48               0.14              0.32     0.98
 regression  medium_productions         False                  none       random_forest_regressor StandardScaler 100.69               0.10              0.35     4.69
 regression  medium_productions          True               complex       random_forest_regressor   RobustScaler   1.22               0.16              0.12    16.71
 regression  medium_productions          True                  none       random_forest_regressor   RobustScaler   1.28               0.12              0.13     3.37
 regression   small_productions         False               complex       random_forest_regressor   RobustScaler 230.48               0.13              0.17    77.05
 regression   small_productions         False                  none       random_forest_regressor StandardScaler 245.05               0.13              0.16    10.21
 regression   small_productions          True               complex             xgboost_regressor   RobustScaler   1.34               0.11              0.11    64.23
 regression   small_productions          True                  none       random_forest_regressor   RobustScaler   1.32               0.12              0.11     3.75

In [14]:
print(
    result_class.to_string(
        index=False, justify="center", float_format="%.2f", decimal="."
    )
)

     problem_type        dataset_name     has_outliers_removed feature_engineering        model_type            scaler      F1 Score  Accuracy  Precision  Recall  duration
binary_classification               full         False               complex             xgboost_classifier StandardScaler    0.62      0.75      0.68      0.56    53.90
binary_classification               full         False                  none       random_forest_classifier StandardScaler    0.62      0.70      0.57      0.68    11.76
binary_classification               full          True               complex             xgboost_classifier   RobustScaler    0.54      0.69      0.64      0.46    51.48
binary_classification               full          True                  none       random_forest_classifier StandardScaler    0.60      0.67      0.57      0.63     7.73
binary_classification  large_productions         False               complex       random_forest_classifier   RobustScaler    0.66      0.72      0.63      0.70    14.61
binary_classification  large_productions         False                  none       random_forest_classifier   RobustScaler    0.63      0.66      0.55      0.73     6.19
binary_classification  large_productions          True               complex       random_forest_classifier StandardScaler    0.59      0.70      0.60      0.57    12.55
binary_classification  large_productions          True                  none       random_forest_classifier StandardScaler    0.60      0.66      0.53      0.69     5.34
binary_classification medium_productions         False               complex             xgboost_classifier   MinMaxScaler    0.60      0.78      0.66      0.54    12.02
binary_classification medium_productions         False                  none       random_forest_classifier   RobustScaler    0.59      0.73      0.55      0.65     5.40
binary_classification medium_productions          True               complex       decision_tree_classifier StandardScaler    0.54      0.68      0.46      0.66     1.47
binary_classification medium_productions          True                  none       decision_tree_classifier StandardScaler    0.57      0.68      0.46      0.75     0.13
binary_classification  small_productions         False               complex       random_forest_classifier   RobustScaler    0.57      0.70      0.56      0.59    16.25
binary_classification  small_productions         False                  none             xgboost_classifier   MinMaxScaler    0.54      0.72      0.62      0.48     4.19
binary_classification  small_productions          True               complex       decision_tree_classifier StandardScaler    0.48      0.55      0.44      0.53     0.86
binary_classification  small_productions          True                  none       random_forest_classifier   RobustScaler    0.49      0.61      0.51      0.47     4.79

In [15]:
print(
    result_multi_class.to_string(
        index=False, justify="center", float_format="%.2f", decimal="."
    )
)

       problem_type           dataset_name     has_outliers_removed feature_engineering        model_type            scaler      F1 Score  Accuracy  Precision  Recall  duration
multi_class_classification               full         False               complex             xgboost_classifier   MinMaxScaler    0.56      0.61      0.53      0.61    227.63
multi_class_classification               full         False                  none             xgboost_classifier   MinMaxScaler    0.53      0.59      0.50      0.59     33.30
multi_class_classification               full          True               complex             xgboost_classifier StandardScaler    0.47      0.52      0.45      0.52    199.63
multi_class_classification               full          True                  none       random_forest_classifier StandardScaler    0.46      0.47      0.45      0.47      8.70
multi_class_classification  large_productions         False               complex             xgboost_classifier   MinMaxScaler    0.54      0.59      0.52      0.59     88.19
multi_class_classification  large_productions         False                  none            logistic_regression   MinMaxScaler    0.49      0.52      0.50      0.52      0.70
multi_class_classification  large_productions          True               complex             xgboost_classifier   MinMaxScaler    0.49      0.53      0.47      0.53     75.04
multi_class_classification  large_productions          True                  none       random_forest_classifier   RobustScaler    0.46      0.48      0.46      0.48      5.45
multi_class_classification medium_productions         False               complex       random_forest_classifier   RobustScaler    0.60      0.63      0.60      0.63      9.09
multi_class_classification medium_productions         False                  none       decision_tree_classifier   MinMaxScaler    0.57      0.61      0.56      0.61      0.17
multi_class_classification medium_productions          True               complex             xgboost_classifier   MinMaxScaler    0.48      0.53      0.45      0.53     33.08
multi_class_classification medium_productions          True                  none            logistic_regression   RobustScaler    0.46      0.55      0.40      0.55      0.30
multi_class_classification  small_productions         False               complex             xgboost_classifier   RobustScaler    0.59      0.63      0.57      0.63    105.46
multi_class_classification  small_productions         False                  none             xgboost_classifier   MinMaxScaler    0.57      0.61      0.55      0.61     13.45
multi_class_classification  small_productions          True               complex             xgboost_classifier StandardScaler    0.40      0.43      0.38      0.43     35.28
multi_class_classification  small_productions          True                  none       random_forest_classifier   RobustScaler    0.39      0.40      0.39      0.40      4.78

In [16]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df,
    problem_type="binary_classification",
    metric="F1 Score",
    metric_agg="max",
    print_stats=True,
    filename_prefix="step_4",
)

          dataset_name  has_outliers_removed feature_engineering  F1 Score
0                 full                 False             complex  0.616561
1                 full                 False                none  0.618414
2                 full                  True             complex  0.538462
3                 full                  True                none  0.603145
4    large_productions                 False             complex  0.661932
5    large_productions                 False                none  0.630631
6    large_productions                  True             complex  0.585859
7    large_productions                  True                none  0.597270
8   medium_productions                 False             complex  0.596226
9   medium_productions                 False                none  0.594937
10  medium_productions                  True             complex  0.539683
11  medium_productions                  True                none  0.568627
12   small_productions                 False             complex  0.573664
13   small_productions                 False                none  0.539730
14   small_productions                  True             complex  0.480519
15   small_productions                  True                none  0.488722

In [17]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df,
    problem_type="multi_class_classification",
    metric="F1 Score",
    metric_agg="max",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering  F1 Score
0                 full                 False             complex  0.558152
1                 full                 False                none  0.532624
2                 full                  True             complex  0.472342
3                 full                  True                none  0.462961
4    large_productions                 False             complex  0.535154
5    large_productions                 False                none  0.494210
6    large_productions                  True             complex  0.490040
7    large_productions                  True                none  0.463461
8   medium_productions                 False             complex  0.604329
9   medium_productions                 False                none  0.569722
10  medium_productions                  True             complex  0.484309
11  medium_productions                  True                none  0.459882
12   small_productions                 False             complex  0.587740
13   small_productions                 False                none  0.565927
14   small_productions                  True             complex  0.397063
15   small_productions                  True                none  0.390286

In [18]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df, problem_type="regression", metric="MAPE", metric_agg="min",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering        MAPE
0                 full                 False             complex  480.921797
1                 full                 False                none  895.483216
2                 full                  True             complex    0.931262
3                 full                  True                none    1.051312
4    large_productions                 False             complex    1.230537
5    large_productions                 False                none    1.260978
6    large_productions                  True             complex    0.941497
7    large_productions                  True                none    1.055972
8   medium_productions                 False             complex   50.476319
9   medium_productions                 False                none  100.686853
10  medium_productions                  True             complex    1.222197
11  medium_productions                  True                none    1.279034
12   small_productions                 False             complex  230.482416
13   small_productions                 False                none  245.054799
14   small_productions                  True             complex    1.342304
15   small_productions                  True                none    1.324875

In [19]:
plot_one_metric_of_different_datasets_per_feature_engineering_outliers_with_plotly(
    experiment_df, problem_type="regression", metric="R2", metric_agg="max",
    print_stats=True,
        filename_prefix="step_4"

)

          dataset_name  has_outliers_removed feature_engineering        R2
0                 full                 False             complex  0.492010
1                 full                 False                none  0.512143
2                 full                  True             complex  0.699462
3                 full                  True                none  0.710483
4    large_productions                 False             complex  0.635562
5    large_productions                 False                none  0.569577
6    large_productions                  True             complex  0.657090
7    large_productions                  True                none  0.650231
8   medium_productions                 False             complex  0.318871
9   medium_productions                 False                none  0.352631
10  medium_productions                  True             complex  0.127610
11  medium_productions                  True                none  0.126435
12   small_productions                 False             complex  0.217955
13   small_productions                 False                none  0.196237
14   small_productions                  True             complex  0.107738
15   small_productions                  True                none  0.107412

In [20]:
plot_one_metric_of_different_models_per_dataset_with_plotly(
    experiment_df,
    problem_type="regression",
    metric="R2",
    metric_agg="max",
    benchmark_model="dummy_regressor",
    print_stats=True,
        filename_prefix="step_4"

)

         dataset_name feature_engineering  has_outliers_removed  \
0                full             complex                 False
1                full             complex                 False
2                full             complex                 False
3                full             complex                 False
4                full             complex                  True
..                ...                 ...                   ...
59  small_productions                none                 False
60  small_productions                none                  True
61  small_productions                none                  True
62  small_productions                none                  True
63  small_productions                none                  True

                 model_type        R2          group
0   decision_tree_regressor  0.436777  complex_False
1           dummy_regressor -0.089893  complex_False
2   random_forest_regressor  0.492010  complex_False
3         xgboost_regressor  0.490310  complex_False
4   decision_tree_regressor  0.633892   complex_True
..                      ...       ...            ...
59        xgboost_regressor  0.132664     none_False
60  decision_tree_regressor  0.014560      none_True
61          dummy_regressor -0.158557      none_True
62  random_forest_regressor  0.107412      none_True
63        xgboost_regressor  0.070538      none_True

[64 rows x 6 columns]

In [21]:
plot_one_metric_of_different_models_per_dataset_with_plotly(
    experiment_df,
    problem_type="regression",
    metric="MAPE",
    metric_agg="min",
    benchmark_model="dummy_regressor",
    print_stats=True,
        filename_prefix="step_4"

)

         dataset_name feature_engineering  has_outliers_removed  \
0                full             complex                 False
1                full             complex                 False
2                full             complex                 False
3                full             complex                 False
4                full             complex                  True
..                ...                 ...                   ...
59  small_productions                none                 False
60  small_productions                none                  True
61  small_productions                none                  True
62  small_productions                none                  True
63  small_productions                none                  True

                 model_type          MAPE          group
0   decision_tree_regressor    614.325576  complex_False
1           dummy_regressor  58612.773083  complex_False
2   random_forest_regressor    768.128887  complex_False
3         xgboost_regressor    480.921797  complex_False
4   decision_tree_regressor      1.174882   complex_True
..                      ...           ...            ...
59        xgboost_regressor   3015.982217     none_False
60  decision_tree_regressor      1.575628      none_True
61          dummy_regressor      2.772113      none_True
62  random_forest_regressor      1.324875      none_True
63        xgboost_regressor      1.508185      none_True

[64 rows x 6 columns]

In [22]:
plot_one_metric_of_different_models_per_dataset_with_plotly(
    experiment_df,
    problem_type="binary_classification",
    metric="F1 Score",
    metric_agg="max",
    benchmark_model="dummy_classifier",
    print_stats=True,
        filename_prefix="step_4"

)

         dataset_name feature_engineering  has_outliers_removed  \
0                full             complex                 False
1                full             complex                 False
2                full             complex                 False
3                full             complex                 False
4                full             complex                 False
..                ...                 ...                   ...
75  small_productions                none                  True
76  small_productions                none                  True
77  small_productions                none                  True
78  small_productions                none                  True
79  small_productions                none                  True

                  model_type  F1 Score          group
0   decision_tree_classifier  0.587384  complex_False
1           dummy_classifier  0.364363  complex_False
2        logistic_regression  0.515406  complex_False
3   random_forest_classifier  0.607336  complex_False
4         xgboost_classifier  0.616561  complex_False
..                       ...       ...            ...
75  decision_tree_classifier  0.348936      none_True
76          dummy_classifier  0.377778      none_True
77       logistic_regression  0.131737      none_True
78  random_forest_classifier  0.488722      none_True
79        xgboost_classifier  0.357798      none_True

[80 rows x 6 columns]

In [23]:
# Load the data

# Example usage
problem_types = ["binary_classification", "multi_class_classification"]
groupby_columns = ["dataset_name", "has_outliers_removed", "feature_engineering"]
metrics = {
    "binary_classification": {"metric": "F1 Score", "operation": "max"},
    "multi_class_classification": {"metric": "F1 Score", "operation": "max"},
}

plot_best_confusion_matrices_from_metadata(
    experiment_df=experiment_df,
    conf_matrix_df=conf_matrix_df,
    problem_types=problem_types,
    groupby_columns=groupby_columns,
    metrics=metrics,
    display_chart=True,
    print_stats=True,
    filename_prefix="step_4"
)

Processing binary_classification...

Confusion Matrix:
          Bankrupt  Success
Bankrupt    1341.0    228.0
Success      374.0    484.0

Total samples: 2427

Confusion Matrix:
          Bankrupt  Success
Bankrupt    1129.0    440.0
Success      277.0    581.0

Total samples: 2427

Confusion Matrix:
          Bankrupt  Success
Bankrupt     673.0    132.0
Success      276.0    238.0

Total samples: 1319

Confusion Matrix:
          Bankrupt  Success
Bankrupt     564.0    241.0
Success      188.0    326.0

Total samples: 1319

Confusion Matrix:
          Bankrupt  Success
Bankrupt     383.0    137.0
Success      101.0    233.0

Total samples: 854

Confusion Matrix:
          Bankrupt  Success
Bankrupt     322.0    198.0
Success       89.0    245.0

Total samples: 854

Confusion Matrix:
          Bankrupt  Success
Bankrupt     365.0     75.0
Success      127.0    127.0

Total samples: 694

Confusion Matrix:
          Bankrupt  Success
Bankrupt     283.0    157.0
Success       79.0    175.0

Total samples: 694

Confusion Matrix:
          Bankrupt  Success
Bankrupt     295.0     41.0
Success       66.0     79.0

Total samples: 481

Confusion Matrix:
          Bankrupt  Success
Bankrupt     259.0     77.0
Success       51.0     94.0

Total samples: 481

Confusion Matrix:
          Bankrupt  Success
Bankrupt     135.0     61.0
Success       26.0     51.0

Total samples: 273

Confusion Matrix:
          Bankrupt  Success
Bankrupt     127.0     69.0
Success       19.0     58.0

Total samples: 273

Confusion Matrix:
          Bankrupt  Success
Bankrupt     546.0    171.0
Success      156.0    220.0

Total samples: 1093

Confusion Matrix:
          Bankrupt  Success
Bankrupt     606.0    111.0
Success      196.0    180.0

Total samples: 1093

Confusion Matrix:
          Bankrupt  Success
Bankrupt     119.0     95.0
Success       65.0     74.0

Total samples: 353

Confusion Matrix:
          Bankrupt  Success
Bankrupt     152.0     62.0
Success       74.0     65.0

Total samples: 353

Processing multi_class_classification...

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          917.0  39.0         185.0            1.0
Flop              203.0  16.0         134.0            2.0
Huge Success      209.0  32.0         546.0            3.0
Small Success      69.0  10.0          60.0            1.0

Total samples: 2427

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          910.0  15.0         217.0            0.0
Flop              208.0   7.0         140.0            0.0
Huge Success      252.0  14.0         522.0            2.0
Small Success      70.0   3.0          67.0            0.0

Total samples: 2427

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          382.0  33.0          97.0            1.0
Flop              136.0  22.0          83.0            2.0
Huge Success      142.0  43.0         278.0            5.0
Small Success      39.0   8.0          48.0            0.0

Total samples: 1319

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          326.0  64.0          98.0           25.0
Flop               98.0  38.0          87.0           20.0
Huge Success      111.0  63.0         256.0           38.0
Small Success      29.0   9.0          51.0            6.0

Total samples: 1319

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          250.0  20.0          61.0            2.0
Flop               69.0  16.0          64.0            3.0
Huge Success       52.0  15.0         233.0            3.0
Small Success      22.0   8.0          35.0            1.0

Total samples: 854

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          198.0  16.0          79.0           40.0
Flop               42.0  10.0          86.0           14.0
Huge Success       38.0  16.0         225.0           24.0
Small Success      15.0   2.0          38.0           11.0

Total samples: 854

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          200.0  21.0          52.0            0.0
Flop               65.0  19.0          46.0            3.0
Huge Success       58.0  21.0         152.0            1.0
Small Success      24.0   5.0          27.0            0.0

Total samples: 694

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          166.0  22.0          63.0           22.0
Flop               53.0  18.0          46.0           16.0
Huge Success       44.0  28.0         141.0           19.0
Small Success      17.0   9.0          24.0            6.0

Total samples: 694

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          200.0  12.0          48.0            0.0
Flop               40.0  10.0          19.0            1.0
Huge Success       31.0   8.0          92.0            3.0
Small Success       8.0   2.0           6.0            1.0

Total samples: 481

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          211.0  11.0          38.0            0.0
Flop               46.0   6.0          18.0            0.0
Huge Success       55.0   1.0          78.0            0.0
Small Success      11.0   0.0           6.0            0.0

Total samples: 481

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          100.0  12.0          15.0            0.0
Flop               30.0   4.0          24.0            0.0
Huge Success       18.0  10.0          42.0            0.0
Small Success       7.0   2.0           9.0            0.0

Total samples: 273

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          106.0   0.0          21.0            0.0
Flop               36.0   0.0          22.0            0.0
Huge Success       26.0   0.0          44.0            0.0
Small Success      11.0   0.0           7.0            0.0

Total samples: 273

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          470.0   5.0          77.0            1.0
Flop               67.0  11.0          61.0            0.0
Huge Success      129.0  19.0         209.0            0.0
Small Success      18.0   1.0          25.0            0.0

Total samples: 1093

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt          463.0   7.0          83.0            0.0
Flop               79.0   8.0          52.0            0.0
Huge Success      146.0  10.0         199.0            2.0
Small Success      16.0   0.0          28.0            0.0

Total samples: 1093

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt           92.0  10.0          38.0            0.0
Flop               32.0   9.0          20.0            1.0
Huge Success       63.0  13.0          51.0            0.0
Small Success      14.0   1.0           9.0            0.0

Total samples: 353

Confusion Matrix:
               Bankrupt  Flop  Huge Success  Small Success
Bankrupt           79.0  20.0          38.0            3.0
Flop               19.0  14.0          24.0            5.0
Huge Success       46.0  26.0          47.0            8.0
Small Success      11.0   7.0           6.0            0.0

Total samples: 353

In [24]:
plot_best_regression_results_from_metadata(
    experiment_df=experiment_df,
    display_chart=True,
    print_stats=True,
    filename_prefix="step_4"
)

🔍 Finding best models using MAPE (min)

📈 Found 16 best models:

• Dataset: full
  Model: xgboost_regressor
  MAPE: 48092.2%
  MAE: $43,653,017
  R²: 0.490

• Dataset: full
  Model: random_forest_regressor
  MAPE: 89548.3%
  MAE: $43,179,763
  R²: 0.512

• Dataset: full
  Model: xgboost_regressor
  MAPE: 93.1%
  MAE: $44,460,731
  R²: 0.668

• Dataset: full
  Model: random_forest_regressor
  MAPE: 105.1%
  MAE: $45,351,088
  R²: 0.710

• Dataset: large_productions
  Model: random_forest_regressor
  MAPE: 123.1%
  MAE: $89,268,295
  R²: 0.551

• Dataset: large_productions
  Model: random_forest_regressor
  MAPE: 126.1%
  MAE: $91,966,523
  R²: 0.552

• Dataset: large_productions
  Model: xgboost_regressor
  MAPE: 94.1%
  MAE: $72,024,168
  R²: 0.656

• Dataset: large_productions
  Model: random_forest_regressor
  MAPE: 105.6%
  MAE: $75,878,913
  R²: 0.650

• Dataset: medium_productions
  Model: decision_tree_regressor
  MAPE: 5047.6%
  MAE: $26,727,601
  R²: 0.319

• Dataset: medium_productions
  Model: random_forest_regressor
  MAPE: 10068.7%
  MAE: $25,613,343
  R²: 0.353

• Dataset: medium_productions
  Model: random_forest_regressor
  MAPE: 122.2%
  MAE: $19,644,027
  R²: 0.119

• Dataset: medium_productions
  Model: random_forest_regressor
  MAPE: 127.9%
  MAE: $19,923,185
  R²: 0.126

• Dataset: small_productions
  Model: random_forest_regressor
  MAPE: 23048.2%
  MAE: $9,700,921
  R²: 0.175

• Dataset: small_productions
  Model: random_forest_regressor
  MAPE: 24505.5%
  MAE: $9,923,759
  R²: 0.156

• Dataset: small_productions
  Model: xgboost_regressor
  MAPE: 134.2%
  MAE: $7,164,587
  R²: 0.108

• Dataset: small_productions
  Model: random_forest_regressor
  MAPE: 132.5%
  MAE: $7,126,486
  R²: 0.107

📊 Model Performance Summary:
• Average Error: $43,653,017
• Typical Error Range: 48092.2% of actual value
• Bias: Model tends to underestimate by $24,945,441
• Error Distribution: 50% of predictions are within $1,990,582 to $34,233,768 of actual value

📊 Model Performance Summary:
• Average Error: $43,179,763
• Typical Error Range: 89548.3% of actual value
• Bias: Model tends to underestimate by $24,459,725
• Error Distribution: 50% of predictions are within $1,906,492 to $35,466,116 of actual value

📊 Model Performance Summary:
• Average Error: $44,460,731
• Typical Error Range: 93.1% of actual value
• Bias: Model tends to underestimate by $22,213,011
• Error Distribution: 50% of predictions are within $4,714,524 to $43,701,771 of actual value

📊 Model Performance Summary:
• Average Error: $45,351,088
• Typical Error Range: 105.1% of actual value
• Bias: Model tends to underestimate by $22,442,634
• Error Distribution: 50% of predictions are within $5,283,498 to $51,151,220 of actual value

📊 Model Performance Summary:
• Average Error: $89,268,295
• Typical Error Range: 123.1% of actual value
• Bias: Model tends to underestimate by $50,899,970
• Error Distribution: 50% of predictions are within $13,175,508 to $98,045,868 of actual value

📊 Model Performance Summary:
• Average Error: $91,966,523
• Typical Error Range: 126.1% of actual value
• Bias: Model tends to underestimate by $40,376,232
• Error Distribution: 50% of predictions are within $15,441,960 to $103,173,105 of actual value

📊 Model Performance Summary:
• Average Error: $72,024,168
• Typical Error Range: 94.1% of actual value
• Bias: Model tends to underestimate by $31,095,130
• Error Distribution: 50% of predictions are within $15,868,408 to $83,839,525 of actual value

📊 Model Performance Summary:
• Average Error: $75,878,913
• Typical Error Range: 105.6% of actual value
• Bias: Model tends to underestimate by $27,911,774
• Error Distribution: 50% of predictions are within $16,225,520 to $95,996,504 of actual value

📊 Model Performance Summary:
• Average Error: $26,727,601
• Typical Error Range: 5047.6% of actual value
• Bias: Model tends to underestimate by $15,220,630
• Error Distribution: 50% of predictions are within $2,737,158 to $27,931,045 of actual value

📊 Model Performance Summary:
• Average Error: $25,613,343
• Typical Error Range: 10068.7% of actual value
• Bias: Model tends to underestimate by $14,382,553
• Error Distribution: 50% of predictions are within $3,255,120 to $27,777,174 of actual value

📊 Model Performance Summary:
• Average Error: $19,644,027
• Typical Error Range: 122.2% of actual value
• Bias: Model tends to underestimate by $9,532,217
• Error Distribution: 50% of predictions are within $5,433,517 to $23,487,347 of actual value

📊 Model Performance Summary:
• Average Error: $19,923,185
• Typical Error Range: 127.9% of actual value
• Bias: Model tends to underestimate by $9,072,004
• Error Distribution: 50% of predictions are within $6,408,403 to $22,464,625 of actual value

📊 Model Performance Summary:
• Average Error: $9,700,921
• Typical Error Range: 23048.2% of actual value
• Bias: Model tends to underestimate by $7,884,417
• Error Distribution: 50% of predictions are within $417,132 to $6,819,059 of actual value

📊 Model Performance Summary:
• Average Error: $9,923,759
• Typical Error Range: 24505.5% of actual value
• Bias: Model tends to underestimate by $7,375,103
• Error Distribution: 50% of predictions are within $531,126 to $6,817,820 of actual value

📊 Model Performance Summary:
• Average Error: $7,164,587
• Typical Error Range: 134.2% of actual value
• Bias: Model tends to underestimate by $3,896,622
• Error Distribution: 50% of predictions are within $1,524,642 to $9,058,361 of actual value

📊 Model Performance Summary:
• Average Error: $7,126,486
• Typical Error Range: 132.5% of actual value
• Bias: Model tends to underestimate by $4,034,631
• Error Distribution: 50% of predictions are within $1,488,848 to $8,929,473 of actual value